resources:
  - name: goServiceGitRepo
    type: GitRepo
    configuration:
      path: danielezer/swampup-go-service
      gitProvider: git

  - name: goServiceDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: goServicePromotedDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: javaBackendGitRepo
    type: GitRepo
    configuration:
      path: danielezer/swampup-java-backend-service
      gitProvider: git

  - name: javaBackendDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: javaBackendPromotedDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: npmFrontendGitRepo
    type: GitRepo
    configuration:
      path: danielezer/swampup-vue-frontend
      gitProvider: git

  - name: appReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: appDistributionRuleToAll
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

pipelines:
  - name: go-service-pipeline
    steps:
      - name: go-service-docker-build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 35.196.150.45:8081/team1-docker-dev-us/gosvc
          dockerImageTag: $run_number
          inputResources:
            - name: goServiceGitRepo
          integrations:
            - name: art

      - name: go-service-docker-push
        type: DockerPush
        configuration:
          targetRepository: team1-docker-dev-us
          autoPublishBuildInfo: true
          integrations:
            - name: art
          inputSteps:
            - name: go-service-docker-build
          outputResources:
            - name: goServiceDockerBuildInfo

      - name: promote-go-service-build
        type: PromoteBuild
        configuration:
          targetRepository: team1-docker-prod-us
          integrations:
            - name: art
          inputResources:
            - name: goServiceDockerBuildInfo
          outputResources:
            - name: goServicePromotedDockerBuildInfo

  - name: npm-maven-service-pipeline
    steps:
      - name: backend-maven-build
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: javaBackendGitRepo
          integrations:
            - name: art
        execution:
          onFailure:
            - jfrog rt config show


      - name: frontend-npm-build
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: .
          repositoryName: team2-npm
          inputResources:
            - name: npmFrontendGitRepo
          integrations:
            - name: art

      - name: frontend-npm-pack
        type: Bash
        configuration:
          inputSteps:
            - name: frontend-npm-build
          integrations:
            - name: art
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: frontend-npm-publish
        type: NpmPublish
        configuration:
          repositoryName: team2-npm-dev-us
          autoPublishBuildInfo: true
          inputSteps:
            - name: frontend-npm-pack
          integrations:
            - name: art
        execution:
          onStart:
            - export inputNpmBuildStepName="frontend-npm-build"

      - name: app-docker-build
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: 35.196.150.45:8081/team1-docker-dev-us/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: javaBackendGitRepo
          inputSteps:
            - name: backend-maven-build
            - name: frontend-npm-publish
          integrations:
            - name: art
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_art_url --user $int_art_user --apikey $int_art_apikey --interactive=false
            - pushd $res_javaBackendGitRepo_resourcePath
            - echo $int_art_url
            - echo $run_Number
            - add_run_variables buildStepName=${step_name} ${step_name}_buildNumber=${run_number} ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_art_url} --build-arg NPM_REPO_NAME=team2-npm-dev-us --build-arg MAVEN_REPO_NAME=team1-mvn-dev-us --build-arg REGISTRY_USERNAME=$int_art_user --build-arg REGISTRY_PASSWORD=$int_art_apikey .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push $dockerImageName:$dockerImageTag team1-docker-dev-us --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

      - name: app-push-build-info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: app-docker-build
          outputResources:
            - name: javaBackendDockerBuildInfo

      - name: app-promote-build-info
        type: PromoteBuild
        configuration:
          targetRepository: team1-docker-prod-us
          integrations:
            - name: art
          inputResources:
            - name: javaBackendDockerBuildInfo
          outputResources:
            - name: javaBackendPromotedDockerBuildInfo

  - name: release-pipeline
    steps:
      - name: create-release-bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo-app
          releaseBundleVersion: 2.0.2
          dryRun: false
          sign: true
          inputResources:
            - name: goServicePromotedDockerBuildInfo
            - name: javaBackendPromotedDockerBuildInfo
          outputResources:
            - name: appReleaseBundle
        execution:
          onStart:
            - echo $outputReleaseBundleResourceName
            - printenv

      - name: distribute-release-bundle
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: appReleaseBundle
            - name: appDistributionRuleToAll
          integrations:
            - name: art
