resources:
  - name: go_gitRepo_demo
    type: GitRepo
    configuration:
      path: danielezer/swampup-go-service
      gitProvider: git

  - name: svc_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: backend_gitRepo_demo
    type: GitRepo
    configuration:
      path: danielezer/swampup-java-backend-service
      gitProvider: git

  - name: app_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: app_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: frontend_gitRepo_demo
    type: GitRepo
    configuration:
      path: danielezer/swampup-vue-frontend
      gitProvider: git

  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

pipelines:
  - name: demo_service_demo
    steps:
      - name: bld_svc_demo
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 35.196.150.45:8081/team1-docker-dev-us/gosvc
          dockerImageTag: $run_number
          inputResources:
            - name: go_gitRepo_demo
          integrations:
            - name: art

      - name: push_svc_demo
        type: DockerPush
        configuration:
          targetRepository: team1-docker-dev-us
          autoPublishBuildInfo: true
          integrations:
            - name: art
          inputSteps:
            - name: bld_svc_demo
          outputResources:
            - name: svc_build_info_demo

      - name: promote_svc_build_demo
        type: PromoteBuild
        configuration:
          targetRepository: team1-docker-prod-us
          integrations:
            - name: art
          inputResources:
            - name: svc_build_info_demo
          outputResources:
            - name: svc_promoted_build_info_demo

  - name: demo_app_pipeline
    steps:
      - name: bld_backend_demo
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: backend_gitRepo_demo
          integrations:
            - name: art
        execution:
          onFailure:
            - jfrog rt config show


      - name: bld_frontend
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: .
          repositoryName: team2-npm
          inputResources:
            - name: frontend_gitRepo_demo
          integrations:
            - name: art

      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend_demo
        type: NpmPublish
        configuration:
          repositoryName: team2-npm-dev-us
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app_demo
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: 35.196.150.45:8081/team1-docker-dev-us/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: backend_gitRepo_demo
          inputSteps:
            - name: bld_backend_demo
            - name: publish_frontend_demo
          integrations:
            - name: art
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_art_url --user $int_art_user --apikey $int_art_apikey --interactive=false
            - pushd $res_backend_gitRepo_demo_resourcePath
            - echo $int_art_url
            - echo $run_Number
            - add_run_variables buildStepName=${step_name} ${step_name}_buildNumber=${run_number} ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_art_url} --build-arg NPM_REPO_NAME=team2-npm-dev-us --build-arg MAVEN_REPO_NAME=team1-mvn-dev-us --build-arg REGISTRY_USERNAME=$int_art_user --build-arg REGISTRY_PASSWORD=$int_art_apikey .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push $dockerImageName:$dockerImageTag team1-docker-dev-us --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

      - name: publish_app_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app_demo
          outputResources:
            - name: app_build_info_demo

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: team1-docker-prod-us
          integrations:
            - name: art
          inputResources:
            - name: app_build_info_demo
          outputResources:
            - name: app_promoted_build_info_demo

  - name: demo_release_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          dryRun: false
          sign: true
          inputResources:
            - name: svc_promoted_build_info_demo
            - name: app_promoted_build_info_demo
          outputResources:
            - name: releaseBundle_demo

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: releaseBundle_demo
            - name: distributionRules_demo
          integrations:
            - name: art
